# Generated by Django 4.2.11 on 2026-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='landing_background',
            field=models.ImageField(blank=True, help_text='Background image for the landing page hero section', null=True, upload_to='backgrounds/'),
        ),
    ]
