# Generated by Django 4.2.11 on 2026-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio_landing_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
